name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/python-app

jobs:
  ci:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}


  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3

      - name: Modify values file
        shell:  bash
        run:  |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          /tmp/yq -i '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app/values.yaml

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update values.yaml with commit ${{needs.ci.outputs.commit_id}}'



      - name: Argo cd app-sync
        shell: bash
        run:  |
          curl -ksSL -o argocd-linux-amd64 https:// argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
          argocd login argocd-server.argocd \
          --insecure --grpc-web --username admin \
          --password ${{  secrets.ARGOCD_PASS  }}
          argocd app sync python-app